const $=id=>document.getElementById(id);let photos=[],dragIndex=null,deferredPrompt=null,currentLot=1;
const DB='CMBAuctionCataloger',STORE='lots';function db(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'lot'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}async function putLot(x){let d=await db();return new Promise((ok,no)=>{let t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(x);t.oncomplete=ok;t.onerror=()=>no(t.error)})}async function allLots(){let d=await db();return new Promise((ok,no)=>{let r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result.sort((a,b)=>a.lot-b.lot));r.onerror=()=>no(r.error)})}async function clearLots(){let d=await db();return new Promise((ok,no)=>{let t=d.transaction(STORE,'readwrite');t.objectStore(STORE).clear();t.oncomplete=ok;t.onerror=()=>no(t.error)})}
function updateNet(){$('net').textContent=navigator.onLine?'Online • local storage active':'Offline • local storage active'}addEventListener('online',updateNet);addEventListener('offline',updateNet);updateNet();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('install').classList.remove('hidden')});$('install').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('install').classList.add('hidden')}else alert('On iPhone/iPad: open this site in Safari, tap Share, then Add to Home Screen.')};
function addFiles(fs){[...fs].forEach(f=>{let r=new FileReader();r.onload=()=>{photos.push({data:r.result,main:photos.length===0});renderPhotos()};r.readAsDataURL(f)})}$('camera').onchange=e=>addFiles(e.target.files);$('picker').onchange=e=>addFiles(e.target.files);
function move(from,to){if(from===null||from===to)return;let x=photos.splice(from,1)[0];photos.splice(to,0,x);renderPhotos()}function renderPhotos(){$('photos').innerHTML='';photos.forEach((p,i)=>{let d=document.createElement('div');d.className='photo'+(p.main?' main':'');d.draggable=true;d.innerHTML=`${p.main?'<span class="badge">MAIN</span>':''}<span class="order">${i+1}</span><img src="${p.data}" alt="Lot photo ${i+1}"><div class="photoBtns"><button data-main="${i}">★ Set Main</button><button data-del="${i}">Delete</button></div>`;d.ondragstart=()=>dragIndex=i;d.ondragover=e=>e.preventDefault();d.ondrop=()=>move(dragIndex,i);d.ontouchstart=()=>dragIndex=i;d.ontouchend=()=>{if(dragIndex!==null)dragIndex=null};$('photos').appendChild(d)});document.querySelectorAll('[data-main]').forEach(b=>b.onclick=()=>{photos.forEach((p,j)=>p.main=j===+b.dataset.main);renderPhotos()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{let i=+b.dataset.del,was=photos[i].main;photos.splice(i,1);if(was&&photos[0])photos[0].main=true;renderPhotos()})}
let fields=['title','description','markings','condition','warnings','low','high','valuationNotes','qty'];function addComp(c={}){let d=document.createElement('div');d.className='comp';d.innerHTML=`<div class="compGrid"><input class="ct" placeholder="Comparable item" value="${esc(c.title||'')}"><input class="cp" type="number" placeholder="Sold price" value="${esc(c.price||'')}"><input class="cd" type="date" value="${esc(c.date||'')}"></div><input class="cs" placeholder="Source link" value="${esc(c.source||'')}"><button class="remove">Remove</button>`;d.querySelector('.remove').onclick=()=>d.remove();$('comps').appendChild(d)}function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}function comps(){return [...document.querySelectorAll('.comp')].map(d=>({title:d.querySelector('.ct').value,price:d.querySelector('.cp').value,date:d.querySelector('.cd').value,source:d.querySelector('.cs').value}))}$('addComp').onclick=()=>addComp();addComp();
async function save(next=false){if(!photos.length&&!confirm('This lot has no photos. Save anyway?'))return;let x={lot:currentLot,photos:[...photos],comps:comps(),shipping:$('shipping').checked,updated:new Date().toISOString()};fields.forEach(f=>x[f]=$(f).value);await putLot(x);$('status').textContent=`Lot ${currentLot} saved on this device.`;if(next){currentLot++;localStorage.setItem('cmbCurrentLot',currentLot);$('lotNo').textContent=currentLot;reset()}}$('save').onclick=()=>save(false);$('saveNext').onclick=()=>save(true);
function reset(){photos=[];renderPhotos();fields.forEach(f=>$(f).value=f==='qty'?'1':'');$('shipping').checked=true;$('comps').innerHTML='';addComp();$('aiStatus').textContent='AI service connection is a separate secure-backend step. Your editable fields and warnings are ready.'}
$('newAuction').onclick=async()=>{if(!confirm('Start a new auction at Lot 1? This clears locally stored lots on this device. Export a backup first if you need the current auction.'))return;await clearLots();currentLot=1;localStorage.setItem('cmbCurrentLot','1');$('lotNo').textContent='1';reset();$('status').textContent='New auction started at Lot 1.'};
$('generate').onclick=()=>alert('The editable AI fields are ready, but secure AI photo analysis requires an online backend. A private API key should not be embedded in the PWA.');
function download(name,type,text){let b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}$('exportBackup').onclick=async()=>{let x=await allLots();download('CMB-Auction-Backup.json','application/json',JSON.stringify({version:1,currentLot,lots:x},null,2))};$('exportCSV').onclick=async()=>{let x=await allLots(),q=v=>'"'+String(v??'').replaceAll('"','""')+'"',rows=[['Lot Number','Title','Description','Maker/Markings','Condition','Low Estimate','High Estimate','Quantity','Shipping'].map(q).join(',')];x.forEach(l=>rows.push([l.lot,l.title,l.description,l.markings,l.condition,l.low,l.high,l.qty,l.shipping?'Yes':'No'].map(q).join(',')));download('CMB-Auction-Lots.csv','text/csv',rows.join('\r\n'))};
currentLot=Math.max(1,+(localStorage.getItem('cmbCurrentLot')||1));$('lotNo').textContent=currentLot;
